# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiNetworkTraining.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NetworkTraining(object):
    def setupUi(self, NetworkTraining):
        NetworkTraining.setObjectName("NetworkTraining")
        NetworkTraining.setWindowModality(QtCore.Qt.WindowModal)
        NetworkTraining.resize(800, 600)
        NetworkTraining.setMinimumSize(QtCore.QSize(800, 600))
        NetworkTraining.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        NetworkTraining.setFont(font)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(NetworkTraining)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(NetworkTraining)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.label_10 = QtWidgets.QLabel(NetworkTraining)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(NetworkTraining)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.neuronInput_1 = QtWidgets.QLineEdit(NetworkTraining)
        self.neuronInput_1.setReadOnly(True)
        self.neuronInput_1.setObjectName("neuronInput_1")
        self.verticalLayout_6.addWidget(self.neuronInput_1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(NetworkTraining)
        self.label_9.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.neuronInput_2 = QtWidgets.QLineEdit(NetworkTraining)
        self.neuronInput_2.setReadOnly(False)
        self.neuronInput_2.setObjectName("neuronInput_2")
        self.verticalLayout_5.addWidget(self.neuronInput_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(NetworkTraining)
        self.label_8.setMinimumSize(QtCore.QSize(100, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.neuronInput_3 = QtWidgets.QLineEdit(NetworkTraining)
        self.neuronInput_3.setReadOnly(True)
        self.neuronInput_3.setObjectName("neuronInput_3")
        self.verticalLayout_7.addWidget(self.neuronInput_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.label_6 = QtWidgets.QLabel(NetworkTraining)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(NetworkTraining)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.epochs = QtWidgets.QLineEdit(NetworkTraining)
        self.epochs.setObjectName("epochs")
        self.verticalLayout_3.addWidget(self.epochs)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(NetworkTraining)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.batch_size = QtWidgets.QLineEdit(NetworkTraining)
        self.batch_size.setObjectName("batch_size")
        self.verticalLayout_4.addWidget(self.batch_size)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(NetworkTraining)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.eta = QtWidgets.QLineEdit(NetworkTraining)
        self.eta.setObjectName("eta")
        self.verticalLayout_2.addWidget(self.eta)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(NetworkTraining)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lmbda = QtWidgets.QLineEdit(NetworkTraining)
        self.lmbda.setObjectName("lmbda")
        self.verticalLayout.addWidget(self.lmbda)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(NetworkTraining)
        self.label_11.setMinimumSize(QtCore.QSize(410, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.neuronInput_4 = QtWidgets.QLineEdit(NetworkTraining)
        self.neuronInput_4.setMinimumSize(QtCore.QSize(300, 0))
        self.neuronInput_4.setReadOnly(False)
        self.neuronInput_4.setObjectName("neuronInput_4")
        self.verticalLayout_8.addWidget(self.neuronInput_4)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonTrain = QtWidgets.QPushButton(NetworkTraining)
        self.buttonTrain.setMinimumSize(QtCore.QSize(380, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonTrain.setFont(font)
        self.buttonTrain.setObjectName("buttonTrain")
        self.horizontalLayout_3.addWidget(self.buttonTrain)
        self.buttonExit = QtWidgets.QPushButton(NetworkTraining)
        self.buttonExit.setMinimumSize(QtCore.QSize(380, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonExit.setFont(font)
        self.buttonExit.setObjectName("buttonExit")
        self.horizontalLayout_3.addWidget(self.buttonExit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)

        self.retranslateUi(NetworkTraining)
        QtCore.QMetaObject.connectSlotsByName(NetworkTraining)

    def retranslateUi(self, NetworkTraining):
        _translate = QtCore.QCoreApplication.translate
        NetworkTraining.setWindowTitle(_translate("NetworkTraining", "Обучение нейросети"))
        self.label.setText(_translate("NetworkTraining", "Для обучения нейросети укажите требуемые параметры"))
        self.label_10.setText(_translate("NetworkTraining", "Параметры создания модели нейросети:"))
        self.label_7.setText(_translate("NetworkTraining", "Входной слой (784)"))
        self.neuronInput_1.setText(_translate("NetworkTraining", "784"))
        self.label_9.setText(_translate("NetworkTraining", "Промежуточные слои(впишите числа через пробел, количество чисел - количество скрытых слоёв, их значения - количества нейронов в них"))
        self.neuronInput_2.setText(_translate("NetworkTraining", "100"))
        self.label_8.setText(_translate("NetworkTraining", "Выходной слой (10)"))
        self.neuronInput_3.setText(_translate("NetworkTraining", "10"))
        self.label_6.setText(_translate("NetworkTraining", "Параметры тренировки нейросети:"))
        self.label_3.setText(_translate("NetworkTraining", "Количество эпох"))
        self.epochs.setText(_translate("NetworkTraining", "5"))
        self.label_2.setText(_translate("NetworkTraining", "Размер батча"))
        self.batch_size.setText(_translate("NetworkTraining", "100"))
        self.label_5.setText(_translate("NetworkTraining", "Скорость обучения"))
        self.eta.setText(_translate("NetworkTraining", "0.5"))
        self.label_4.setText(_translate("NetworkTraining", "Параметр регуляризации"))
        self.lmbda.setText(_translate("NetworkTraining", "5.0"))
        self.label_11.setText(_translate("NetworkTraining", "Название файла (директория data/networks в корневой директории программы)"))
        self.neuronInput_4.setText(_translate("NetworkTraining", "networkcreated1"))
        self.buttonTrain.setText(_translate("NetworkTraining", "Обучить нейросеть"))
        self.buttonExit.setText(_translate("NetworkTraining", "Закрыть окно"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NetworkTraining = QtWidgets.QWidget()
    ui = Ui_NetworkTraining()
    ui.setupUi(NetworkTraining)
    NetworkTraining.show()
    sys.exit(app.exec_())
